In [ ]:
import os
import csv
import pandas as pd
import numpy as np
from collections import defaultdict
import pywt

In [ ]:
data_dir = 'C:/Users/M Raheel Safdar/Desktop/raw signals/Unclean Data'

In [ ]:
fout_data = open("train.csv",'a')
vec = []
chan = ['EXG Channel 0', 'EXG Channel 1', 'EXG Channel 2', 'EXG Channel 3']
columns = defaultdict(list)

In [ ]:
train_dir = os.path.join(data_dir, 'train')

for label_type in ['right', 'left', 'forward', 'back', 'up','down']:
	dir_name = os.path.join(train_dir, label_type)
	for fname in os.listdir(dir_name):
		with open(os.path.join(dir_name, fname)) as f:
			reader = csv.DictReader(f)
			for row in reader:	
				for (k,v) in row.items(): 
					print(k + " " + v) 
					columns[k].append(v) 
					print(columns[k])
		for i in chan:
			x = np.array(columns[i]).astype(np.float)
			coeffs = pywt.wavedec(x, 'db4', level=6)
			cA6, cD6, cD5,cD4,cD3,cD2,cD1 = coeffs
			cD5 = np.std(cD5)
			cD4 = np.std(cD4)
			cD3 = np.std(cD3)
			cD2 = np.std(cD2)
			cD1 = np.std(cD1)
			if i =="EXG Channel 3":
				fout_data.write(str(cD5)+",")
				fout_data.write(str(cD4)+",")
				fout_data.write(str(cD3)+",")
				fout_data.write(str(cD2)+",")
				fout_data.write(str(cD1))
			else:
				fout_data.write(str(cD5)+",")
				fout_data.write(str(cD4)+",")
				fout_data.write(str(cD3)+",")
				fout_data.write(str(cD2)+",")
				fout_data.write(str(cD1)+",")
		fout_data.write("\n")
		fout_data.close()

 EXG Channel 0 -109331.81456706698
 EXG Channel 1 -10992.632626608924
 EXG Channel 2 -29975.38804714537
 EXG Channel 3 -40377.10760558934
 EXG Channel 0 -106911.76884314643
 EXG Channel 1 -10966.145809429385
 EXG Channel 2 -29987.83796880698
 EXG Channel 3 -40476.84108934893
 EXG Channel 0 -107944.68765791508
 EXG Channel 1 -11224.576678821646
 EXG Channel 2 -30303.73517319384
 EXG Channel 3 -40388.61875398383
 EXG Channel 0 -110331.9880762086
 EXG Channel 1 -11293.57651395518
 EXG Channel 2 -30316.430964044448
 EXG Channel 3 -40281.77741548746
 EXG Channel 0 -110805.64389296102
 EXG Channel 1 -11170.150181072971
 EXG Channel 2 -30143.339054982556
 EXG Channel 3 -40304.21856692059
 EXG Channel 0 -109260.60190923235
 EXG Channel 1 -11007.27301922715
 EXG Channel 2 -29968.861337764425
 EXG Channel 3 -40389.289306317485
 EXG Channel 0 -106860.04690647684
 EXG Channel 1 -10971.487876354204
 EXG Channel 2 -29994.118808998923
 EXG Channel 3 -40479.18802251673
 EXG Channel 0 -107967.575844237

C:\Users\M Raheel Safdar\AppData\Local\Temp\ipykernel_1004\3036247807.py:13: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(columns[i]).astype(np.float)


ValueError: Value of data_len must be greater than zero.

In [ ]:
print(len(train_texts))
print(len(train_labels))

120
120


In [ ]:
test_labels = []
test_texts = []

test_dir = os.path.join(data_dir, 'test')

for label_type in ['right', 'left', 'forward', 'back', 'up','down']:
    dir_name = os.path.join(test_dir, label_type)
    for fname in os.listdir(dir_name):
        if fname[-4:] == '.csv':
            #print(fname)
            #f = open(os.path.join(dir_name, fname),'rb')
            test_x = np.genfromtxt(os.path.join(dir_name,fname),delimiter=',')
            test_x = np.array(test_x)
            test_texts.append(test_x)
            #f.close()
            if label_type == 'right':
                test_labels.append(0)
            elif label_type == 'left':
                test_labels.append(1)
            elif label_type == 'forward':
                test_labels.append(2)
            elif label_type == 'back':
                test_labels.append(3)
            elif label_type == 'up':
                test_labels.append(4)
            else:
                test_labels.append(5)

In [ ]:
print(len(test_texts))
print(len(test_labels))

In [ ]:
train_texts[0].shape

(2560, 4)

In [ ]:
test_texts[0].shape

(2560, 4)

In [ ]:
train_data = np.array(train_texts, dtype=float)
train_labels = np.array(train_labels)

In [ ]:
train_data[0]

In [ ]:
test_data = np.array(test_texts, dtype=float)
test_labels = np.array(test_labels)

In [ ]:
test_data[0]

array([[         nan,  18997.37346, -42747.4207 , -38719.99398],
       [ 13731.86126,  21631.30303, -43159.47511, -39158.55755],
       [ 15847.7668 ,  24355.19837, -43321.21233, -39298.21125],
       ...,
       [ 15019.05352,  24954.96273, -43027.01867, -39087.25549],
       [ 11601.11417,  21459.75339, -42488.6769 , -38528.19366],
       [ 10386.47567,  19738.28909, -42481.79257, -38546.96912]])

In [ ]:
x_train = test_data[:]
y_train = test_labels[:]

print(x_train.shape)
type(x_train)

(60, 2560, 4)


numpy.ndarray

In [ ]:
x_train[0]

array([[         nan,  18997.37346, -42747.4207 , -38719.99398],
       [ 13731.86126,  21631.30303, -43159.47511, -39158.55755],
       [ 15847.7668 ,  24355.19837, -43321.21233, -39298.21125],
       ...,
       [ 15019.05352,  24954.96273, -43027.01867, -39087.25549],
       [ 11601.11417,  21459.75339, -42488.6769 , -38528.19366],
       [ 10386.47567,  19738.28909, -42481.79257, -38546.96912]])

In [ ]:
nsamples, nx, ny = x_train.shape
x_train = x_train.reshape((nsamples,nx*ny))

x_train.shape


(60, 10240)

In [ ]:
x_train[0]

array([         nan,  18997.37346, -42747.4207 , ...,  19738.28909,
       -42481.79257, -38546.96912])

In [ ]:
x_train = np.nan_to_num(x_train)

In [ ]:
x_train[0]

array([     0.     ,  18997.37346, -42747.4207 , ...,  19738.28909,
       -42481.79257, -38546.96912])

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
model = MLPClassifier(alpha=0.001,epsilon = 1e-08, hidden_layer_sizes=(250, 150), activation='logistic', batch_size=256, learning_rate='invscaling', max_iter=1000)

In [ ]:
model.fit(x_train, y_train)

c:\Users\M Raheel Safdar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:621: UserWarning: Got `batch_size` less than 1 or larger than sample size. It is going to be clipped
  warnings.warn(


MLPClassifier(activation='logistic', alpha=0.001, batch_size=256,
              hidden_layer_sizes=(250, 150), learning_rate='invscaling',
              max_iter=1000)

In [ ]:
y_pred = model.predict(x_test)
#Calculate Accuracy
acc = accuracy_score(y_test, y_pred)
print(acc)

NameError: name 'x_test' is not defined